name: Test

on:
  push:

jobs:
  Test:
    name: Build
    runs-on: ubuntu-latest
    services:
      etcd:
        image: quay.io/coreos/etcd:v3.4.0
      ports:
        - 2379:2379
        - 2380:2380
      options: /usr/local/bin/etcd
        -name etcd01
        -data-dir /etcd-data
        -advertise-client-urls http://etcd01.gsxhnd.xyz:2379
        -listen-client-urls http://0.0.0.0:2379
        -initial-advertise-peer-urls http://etcd01.gsxhnd.xyz:2380
        -listen-peer-urls http://0.0.0.0:2380
        -initial-cluster-token docker-etcd
        -initial-cluster etcd01=http://etcd01.gsxhnd.xyz:2380
        --initial-cluster etcd01=http://etcd01.gsxhnd.xyz:2380
        -initial-cluster-state new
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - run: docker ps -a
      - name: Get dependencies
        run:
          go get -v -t -d ./...
      - name: Test
        run: go test -v -coverprofile=profile.cov ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov