name: Test

on:
  push:

jobs:
  Test:
    name: Build
    runs-on: ubuntu-latest
    services:
      etcd:
        image: quay.io/coreos/etcd:v3.4.0
        ports:
          - 2379:2379
          - 2380:2380
        env:
          NAME: etcd
          DATA-DIR: /etcd-data
          ADVERTISE-CLIENT-URLS: http://etcd:2379
          LISTEN-CLIENT-URLS: http://etcd:2379
          INITIAL-ADVERTISE-PEER-URLS: http://etcd:2380
          LISTEN-PEER-URLS: http://0.0.0.0:2380
          INITIAL-CLUSTER-TOKEN: docker-etcd
          INITIAL-CLUSTER: etcd01=http://etcd:2380
          INITIAL-CLUSTER-STATE: new
        options: >-
          --health-cmd="etcdctl endpoint health"
          --health-start-period 10s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - run: docker ps -a
      - name: Get dependencies
        run:
          go get -v -t -d ./...
      - name: Test
        run: go test -v -coverprofile=profile.cov ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov